name: Windows

on:
  workflow_call:
    
jobs:
  ci:
    runs-on: windows-latest
    steps:
      - name: Set git to use LF
        run: |
          git config -l
          echo "---"
          git config --global core.autocrlf false
          git config --global core.eol lf
          echo "---"
          git config -l
      - name: Support longpaths
        run: git config --system core.longpaths true
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Check LongPathsEnabled
        run: |
          (Get-ItemProperty "HKLM:System\CurrentControlSet\Control\FileSystem").LongPathsEnabled
      - name: Test
        shell: cmd
        run: |
          echo "Welcome to Windows"

          exit /b %errorlevel%
