name: CAmkES

on: 
  workflow_dispatch:
    inputs:
      docker_image:
        type: string
        description: Docker image to fetch (latest used by default)
        default: trustworthysystems/camkes
      verbose:
        type: boolean
        description: Enable verbose testing output
        default: false
env:
  IMAGE: ${{ inputs.docker_image && inputs.docker_image || 'trustworthysystems/camkes' }}
  VERBOSE_DEBUG: ${{ (runner.debug == '1' || inputs.verbose == 'true') && ',verbose' || '' }}
  
jobs:
  container:
    runs-on: ubuntu-latest
    container:
      image: ${{ env.IMAGE }}
    strategy:
      fail-fast: false
      matrix:
        VM_PARTITION: [false]
    name: 'VM Partition=${{ matrix.VM_PARTITION }}'
    steps:
      - name: Build
        env:
          # add verbose flag if workflow is restarted with "enable debug loggin" checked
          VERBOSE_DEBUG: ${{ runner.debug == '1' && ',verbose' || '' }}
        run: |
          # github sets HOME to /github/home but some tools (Sireum's Os.home, Haskell) use
          # the containers /root instead leading to inconsistent installs. Setting HOME
          # to be root resolves the issue
          # https://github.com/actions/runner/issues/1474#issuecomment-965805123

          env

          echo ${{ inputs.docker_image }}
