on:
  push:
  workflow_dispatch:

jobs:
  linux:
    uses: ./.github/workflows/CI_linux.yml
    with: 
      branch_name: '${{ github.run_id }}-${{github.run_attempt}}'
  mac:
    uses: ./.github/workflows/CI-macOS.yml
  win:
    uses: ./.github/workflows/CI-windows.yml
  
  updateRepo:
    runs-on: ubuntu-latest
    needs: [linux, mac, win]
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update
        run: |
          echo "Welcome to the updater"
          export RUN_X='${{ github.run_id }}-${{github.run_attempt}}'
          echo "run number is $RUN_X"
          git pull --all
          git checkout $RUN_X
          git pull
          git checkout main
          git rebase $RUN_X
          git status
          git push
          git push origin --delete $RUN_X
