name: Linux

on:
  workflow_call:
    inputs:
      username:
        default: 'not-sent'
        required: true
        type: string
    
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Test
        run: |
          echo "Welcome to Linux"
          echo "Received: ${{ inputs.username }} "