name: Linux

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
    
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Test
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          echo "Welcome to Linux"
          echo "Received: ${{ inputs.branch_name }} "
          date > date.txt
          git add .
          git commit -m added-stuff
          git push -u origin ${{ inputs.branch_name }}